dataset_dir: /home/emir/Desktop/dev/myResearch/dataset/FoodSeg103
dataset_name: FoodSeg103
arch_name: "vits14"
batch_size: 8
num_workers: 1 # 2
model_name: facebook/dinov2-small
learning_rate: 1e-3
epochs: 50
metric: mIoU
hidden_size: 384
attention_out: ./attention_maps
device: "cuda:0"
patch_size: 14